version: '3'

networks:
  document_system_network:
    driver: bridge

services:
  nginx:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    image: document-system-nginx:0.0.1
    ports:
      - "8080:8080"
    hostname: document-system-nginx
    networks:
      - document_system_network

  mysql:
    build:
      context: .
      dockerfile: docker/mysql/Dockerfile
    image: document-system-db:0.0.1
    ports:
      - "3306:3306"
    hostname: mysql
    networks:
      - document_system_network
    # volumes:
    #   - mysql_data:/var/lib/mysql

  redis:
    build:
      context: .
      dockerfile: docker/redis/Dockerfile
    image: document-system-redis:0.0.1
    ports:
      - "6379:6379"
    hostname: document-system-redis
    networks:
      - document_system_network

  api:
    build:
      context: .
      dockerfile: docker/api/Dockerfile
      args:
        ENVIRONMENT: dev
    image: document-system-api:0.0.1
    ports: 
      - "5000:5000"
    hostname: document-system-api
    networks:
      - document_system_network