apiVersion: v1
kind: ConfigMap
metadata:
  name: document-system-config
  namespace: document-system
data:
  MYSQL_DATABASE: document_system
  MYSQL_USER: admin
  MYSQL_ROOT_PASSWORD: nycu_is_good
  MYSQL_PASSWORD: admin
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: document-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: document-system-nginx:0.0.1
        ports:
        - containerPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: document-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:8.3
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: document-system-config
              key: MYSQL_ROOT_PASSWORD
        - name: MYSQL_DATABASE
          valueFrom:
            configMapKeyRef:
              name: document-system-config
              key: MYSQL_DATABASE
        - name: MYSQL_USER
          valueFrom:
            configMapKeyRef:
              name: document-system-config
              key: MYSQL_USER
        - name: MYSQL_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: document-system-config
              key: MYSQL_PASSWORD
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
  namespace: document-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
      - name: rabbitmq
        image: rabbitmq:3.13-alpine
        ports:
        - containerPort: 5672
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: document-system-deployment
  namespace: document-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: document-system
  template:
    metadata:
      labels:
        app: document-system
    spec:
      containers:

        # volumeMounts:
        # - name: frontend-dist
        #   mountPath: /usr/share/nginx/html
        # - name: frontend
        #   mountPath: /app

      - name: api
        image: document-system-api:0.0.1
        ports:
        - containerPort: 5000
        env:
        - name: SQLALCHEMY_DATABASE_URI
          value: "mysql://root:nycu_is_good@mysql:3306/document_system"

      - name: email-notification-system
        image: document-system-email-notification-system:0.0.1

      # - name: frontend
      #   image: document-system-frontend:0.0.1
      #   volumeMounts:
      #   - name: frontend
      #     mountPath: /app

      volumes:
      # - name: frontend-dist
      #   hostPath:
      #     path: /path/on/host/frontend/dist
      # - name: frontend
      #   hostPath:
      #     path: /path/on/host/frontend
      - name: system
        hostPath:
          path: system
